binary-ghc-args:
- -O
- -threaded
module-template: ! 'module MODULE_NAME where

'
extensions:
  GeneralizedNewtypeDeriving: true
  TemplateHaskell: true
  RecordWildCards: true
  OverloadedStrings: true
  GADTs: true
  EmptyDataDecls: true
  QuasiQuotes: true
  TupleSections: true
  TypeFamilies: true
  DeriveDataTypeable: true
  CPP: true
  MultiParamTypeClasses: true
  ViewPatterns: true
  FlexibleContexts: true
environment: ghc-7.8-stable-14.09
auto-hidden: []
cabal-file: project.cabal
version: 1
extra-packages: ! 'Hackage: wtk 0.2.1

  Git: https://github.com/bartoszw/elca.git fab03a0859d70f697b2405fc54f590317dbb5f18'
ghc-args: []
excluded-modules:
- app/devel.hs
